[package]
name = "timetable_extract"
version = "0.1.0"
edition = "2024"

[dependencies]
calamine = "0.33.0"
genpdf = "0.2.0"
clap = { version = "4.5.57", features = ["derive"] }
# indicatif= "0.18.3"
dirs2 = "3.0.1"

[[bin]]
name = "extract_timetable"
path = "src/main.rs"